export const MSG = {
  PING: "PING",
  PONG: "PONG",
  GET_PAGE_STATE: "GET_PAGE_STATE",
  PAGE_STATE: "PAGE_STATE",

  QUEUE_GET_STATE: "QUEUE_GET_STATE",
  QUEUE_STATE: "QUEUE_STATE",
  QUEUE_ADD_TASKS: "QUEUE_ADD_TASKS",
  QUEUE_REMOVE_TASK: "QUEUE_REMOVE_TASK",
  QUEUE_SKIP_TASK: "QUEUE_SKIP_TASK",
  QUEUE_RETRY_ERRORS: "QUEUE_RETRY_ERRORS",
  QUEUE_CLEAR: "QUEUE_CLEAR",
  QUEUE_CLEAR_HISTORY: "QUEUE_CLEAR_HISTORY",
  QUEUE_START: "QUEUE_START",
  QUEUE_PAUSE: "QUEUE_PAUSE",
  QUEUE_STOP: "QUEUE_STOP",

  SETTINGS_UPDATE: "SETTINGS_UPDATE",

  EXECUTE_TASK: "EXECUTE_TASK",
  TASK_LOG: "TASK_LOG",
  TASK_RESULT: "TASK_RESULT",
  RESET_EXECUTION_SESSION: "RESET_EXECUTION_SESSION",
  REF_MEDIA_LOOKUP: "REF_MEDIA_LOOKUP",
  REF_MEDIA_UPSERT: "REF_MEDIA_UPSERT",
  EXPECT_DOWNLOAD: "EXPECT_DOWNLOAD",
  DOWNLOAD_BY_URL: "DOWNLOAD_BY_URL",
  GET_IMAGE_BLOB: "GET_IMAGE_BLOB",

  // Project management
  PROJECT_LIST: "PROJECT_LIST",
  PROJECT_CREATE: "PROJECT_CREATE",
  PROJECT_RENAME: "PROJECT_RENAME",
  PROJECT_DELETE: "PROJECT_DELETE",
  PROJECT_SWITCH: "PROJECT_SWITCH",
} as const;

export type MsgType = (typeof MSG)[keyof typeof MSG];
